### ISSUE TITLE
Any progress with the project

### ISSUE THREAD

**Issue by omaryasirm** [canewsin/flutter-code-push-timeline#2]
Hi @canewsin. How's the project coming along?

**Comment by canewsin** [comment]
@Omaryasirm 
i was writing main part of it there are some custom parts of it i was wiring up now.

**Comment by omaryasirm** [comment]
@canewsin Ok great. Would you be able to give me a timeline of when you think you will have beta available?

**Comment by canewsin** [comment]
@Omaryasirm may be soon, no timeline since i have 4+ more projects with only me as a developer, also hope you read the ReadMe because code will be licensed for a fee as i stated before. Also one thing to note is codepush requires slight modification of project structure and an simple IDE provided by me. IDE is not compusory but can be timesaver.

**Comment by canewsin** [comment]
i will update progress report on main readme file, thus closing this issue.
